eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
