server:
  port: 19093

spring:
  application:
    name: product-service

  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

management:
  tracing:
    sampling:
      probability: 1.0


