eureka:
  client:
    service-url:
      defaultZone: http://prodendpoint:19090/eureka/

spring:
  datasource:
    url: jdbc:mysql://sparta.cpwmww8igmtu.ap-northeast-2.rds.amazonaws.com:3306/msa_exam
    username: test
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: prodendpoint
      port: 6379
      username: default
      password: systempass

management:
  zipkin:
    tracing:
      endpoint: "http://prodendpoint:9411/api/v2/spans"